[package]
name = "rhai"
version = "0.10.2"
edition = "2018"
authors = ["Jonathan Turner", "Lukáš Hozda", "Stephen Chung"]
description = "Embedded scripting for Rust"
homepage = "https://github.com/jonathandturner/rhai"
repository = "https://github.com/jonathandturner/rhai"
readme = "README.md"
license = "MIT/Apache-2.0"
include = [
    "**/*.rs",
    "scripts/*.rhai",
    "Cargo.toml"
]

[dependencies]
num-traits = "*"

[features]
default = []
debug_msgs = []
unchecked = []
no_stdlib = []
no_index = []

[profile.release]
lto = "fat"
codegen-units = 1
